### ISSUE TITLE
React Native Web support

### ISSUE THREAD

**Issue by Pranit-Harekar** [SocketMobile/react-native-capture#1]
Hi there!

Good job putting out this library, our team definitely needed this. We would like to use this in our [react-native-web](https://necolas.github.io/react-native-web/) app, so will this library work out-of-the box on browsers? We know this uses captureJS under the hood but we aren't sure if this library would support browsers. Have you done any testing on browser? Kindly let us know.

Thank you

**Comment by Pranit-Harekar** [comment]
NVM it looks like you are using Native modules which aren't fully implemented React native web

**Comment by EricGlaenzer** [comment]
Hi @Pranit-Harekar, thank you for your interest in our products. The native part adds our Capture SDK to the iOS code. For Android it's basically checking if the Socket Mobile Companion service is running. The Companion service is a requirement for connecting to our barcode scanners and NFC Reader/Writer. In iOS there is no such service possible and for that reason we have Socket Mobile Rumba, a browser app that bridges our Capture SDK to a web app using CaptureJS library. You can check this link: https://www.npmjs.com/package/socketmobile-capturejs. If you have any questions or specific requirements, feel free to reach us at sdksupport@socketmobile.com
